name: "mainCI"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: string

jobs:
  release-pub:
    name: "release-pub"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      # 把分支拉出来
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      # 指定node版本
      - name: Set node version
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      # 安装依赖，包括我们的 semantic-release 全套
      - name: Install
        run: |
          npm install
      # 打包你的插件/组件/库等等等
      - name: Build
        run: |
          npm run build
      - run: echo ${{ secrets.NPM_TOKEN }}
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release